packages:
  - apps/*
  - packages/*

catalog:
  "@types/node": 25.2.2
  "@types/pg": 8.15.4
  "@vitest/browser-playwright": 4.0.18
  drizzle-orm: 0.45.1
  pg: 8.16.0
  playwright: 1.58.2
  typescript: 5.9.3
  vitest: 4.0.18

onlyBuiltDependencies:
  - esbuild
  - lefthook
